'use strict';

const PARKING_SLOT_STATUS = {
  AVAILABLE: 'Available',
  OCCUPIED: 'Occupied',
};

const PARKING_SPOT_TYPE = {
  S: 'S',
  M: 'M',
  L: 'L'
}

const VEHICLE_AVAILABILITY_LIST = {
  [PARKING_SPOT_TYPE.S]: [
    PARKING_SPOT_TYPE.S,
    PARKING_SPOT_TYPE.M,
    PARKING_SPOT_TYPE.L
  ],
  [PARKING_SPOT_TYPE.M]: [
    PARKING_SPOT_TYPE.M,
    PARKING_SPOT_TYPE.L,
  ],
  [PARKING_SPOT_TYPE.L]: [
    PARKING_SPOT_TYPE.L,
  ],
};

const PARKING_RATE_BY_TYPE = {
  [PARKING_SPOT_TYPE.S]: 20,
  [PARKING_SPOT_TYPE.M]: 60,
  [PARKING_SPOT_TYPE.L]: 100
};

const FLAT_AND_EXCESS_PARKING_RATES = {
  FLAT_RATE: 40,
  EXCESS_HOURS: 5000
}
const RESPONSE_STATUS = {
  SUCCESS: 'success',
  ERROR: 'error',
}

module.exports = {
  PARKING_SLOT_STATUS,
  PARKING_SPOT_TYPE,
  VEHICLE_AVAILABILITY_LIST,
  PARKING_RATE_BY_TYPE,
  FLAT_AND_EXCESS_PARKING_RATES,
  RESPONSE_STATUS
}